import { APPROVED_KART_COMPONENTS } from "./kart-component-registry";
import {
  APPROVED_CONSTRUCTION_MATERIALS,
  APPROVED_SURFACE_MATERIALS,
  APPROVED_TIRE_COMPOUNDS,
  APPROVED_TIRE_SURFACE_INTERACTIONS,
} from "./kart-material-registry";

function definitionSection(definition: {
  id: string;
  label: string;
  summary: string;
  version: number;
}) {
  return [
    `### ${definition.label} — \`${definition.id}@${definition.version}\``,
    "",
    definition.summary,
    "",
    "```json",
    JSON.stringify(definition, null, 2),
    "```",
    "",
  ].join("\n");
}

export function renderKartCatalogReference() {
  const sections = [
    "# Generated Kart Catalog Reference",
    "",
    "> Generated by `pnpm docs:generate-kart-catalog` from the typed registries. Do not edit this file directly.",
    "> Units are SI unless a field name says otherwise. Narrative guidance remains in `components-and-materials.md`.",
    "",
    "## Approved Components",
    "",
    ...APPROVED_KART_COMPONENTS.map(definitionSection),
    "## Construction Materials",
    "",
    ...APPROVED_CONSTRUCTION_MATERIALS.map(definitionSection),
    "## Tire Compounds",
    "",
    ...APPROVED_TIRE_COMPOUNDS.map(definitionSection),
    "## Surface Materials",
    "",
    ...APPROVED_SURFACE_MATERIALS.map(definitionSection),
    "## Tire And Surface Interactions",
    "",
    "```json",
    JSON.stringify(APPROVED_TIRE_SURFACE_INTERACTIONS, null, 2),
    "```",
    "",
  ];
  return sections.join("\n");
}
